---
title: "Class1"
output: github_document
---

```{r setup}
library(tidyverse)
library(tidyr)
library(knitr)
library(ggplot2)
```

```{r}
Sortiment_hela <- read.csv("Class_files/systembolaget2018-10-08.csv")
#head(Sortiment_hela)

Sortiment_ord <- Sortiment_hela %>%
  mutate(Alkoholhalt = as.numeric(gsub("%","",Alkoholhalt))/100) %>%
  mutate(Varugrupp = ifelse(Varugrupp=="Röda", "Rött vin", ifelse(Varugrupp=="Vita", "Vitt vin", levels(Varugrupp)))) %>%
  filter(SortimentText == "Ordinarie sortiment")
#head(Sortiment_ord)

PrisMax <- Sortiment_hela %>%
  filter(PrisPerLiter == max(PrisPerLiter)) %>%
  select(Namn)
PrisMax

Expensive <- Sortiment_ord %>%
  arrange(desc(PrisPerLiter)) %>%
  slice(1:10) %>%
  select(Namn, PrisPerLiter, Varugrupp, Alkoholhalt)
kable(Expensive, format = "html")
```
```{r}
ggplot(Sortiment_ord, aes(x = Alkoholhalt, y = PrisPerLiter, color = Varugrupp)) + 
  geom_point() + 
  scale_y_log10()

ggplot(Sortiment_ord, aes(x = Varugrupp, y = PrisPerLiter)) + 
  geom_point() + 
  scale_y_log10() + 
  coord_flip()

Sortiment_ord %>%
  filter(Varugrupp %in% c("Vitt vin", "R\303\266tt vin", "Ros\303\251vin", "Mousserande vin"), Argang %in% c(2010:2017)) %>%
  ggplot(aes(x = Argang, y = PrisPerLiter, color = Varugrupp)) + geom_point()

Sortiment_ord %>%
  filter(Varugrupp %in% c("Vitt vin", "R\303\266tt vin", "Ros\303\251vin", "Mousserande vin"), Argang %in% c(2010:2017)) %>%
  ggplot(aes(x = Argang, y = PrisPerLiter)) + geom_point() + facet_wrap(~ Varugrupp)
```

```{r}
Film <- read.csv("Class_files/Film_events_2018-11-07.csv")
FilmSO <- Film %>%
  filter(eventTicketStatus=="soldout")
Film %>% 
  group_by(venueId) %>% 
  mutate(N=n()) %>%
  ungroup() %>% 
  filter(N==max(N)) %>%
  slice(1) %>%
  select(venueName)
```

```{r}
ggplot(FilmSO, aes(x = eventDate, y = eventName_en)) + geom_point() 
```
```{r, Olympic winter medals}
winter_medals <- read.csv("Class_files/Winter_medals2018-09-26.csv")
head(winter_medals)

winter_medals <- winter_medals %>%
  mutate(medals_per_mill = 1000000*Total/Population)

winter_medals %>%
  filter(Year == 2018) %>%
  arrange(desc(medals_per_mill)) %>%
  slice(1:10)

medals_SNF <- winter_medals %>%
  filter(Country %in% c("Sweden", "Norway", "Finland"))

ggplot(medals_SNF, aes(x = Year, y = Total, shape = Country, color = Country)) + 
  geom_point() + 
  facet_wrap(~ Country)

medals_Swe <- winter_medals %>%
  filter(Country == "Sweden") %>%
  select(Year, Gold, Silver, Bronze)
total_medals_Swe <- gather(medals_Swe, Medals, value, -Year)
ggplot(total_medals_Swe, aes(x = Year, y = value, color = Medals)) + 
  geom_point() +
  scale_color_manual(breaks = c("Gold", "Silver", "Bronze"), values=c("goldenrod3", "gold", "gray75")) +
  ylab("Medals") 

total_medals_SNF <- medals_SNF %>%
  select(Country, Year, Gold, Silver, Bronze) %>%
  gather(Medals, value, -Year, - Country)
ggplot(total_medals_SNF, aes(x = Year, y = value, color = Medals)) + 
  geom_point() +
  scale_color_manual(breaks = c("Gold", "Silver", "Bronze"), values=c("goldenrod3", "gold", "gray75")) +
  ylab("Medals") +
  facet_wrap(~ Country)
```

